/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.courseselection.kafkatypes;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Course extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7252341331749231105L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Course\",\"namespace\":\"com.courseselection.kafkatypes\",\"fields\":[{\"name\":\"id\",\"type\":[\"int\",\"null\"]},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"code\",\"type\":\"string\"},{\"name\":\"professorId\",\"type\":\"int\"},{\"name\":\"capacity\",\"type\":\"int\"},{\"name\":\"enrolled\",\"type\":[\"int\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Course> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Course> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Course> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Course> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Course> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Course to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Course from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Course instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Course fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.Integer id;
  private java.lang.CharSequence name;
  private java.lang.CharSequence code;
  private int professorId;
  private int capacity;
  private java.lang.Integer enrolled;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Course() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param name The new value for name
   * @param code The new value for code
   * @param professorId The new value for professorId
   * @param capacity The new value for capacity
   * @param enrolled The new value for enrolled
   */
  public Course(java.lang.Integer id, java.lang.CharSequence name, java.lang.CharSequence code, java.lang.Integer professorId, java.lang.Integer capacity, java.lang.Integer enrolled) {
    this.id = id;
    this.name = name;
    this.code = code;
    this.professorId = professorId;
    this.capacity = capacity;
    this.enrolled = enrolled;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return code;
    case 3: return professorId;
    case 4: return capacity;
    case 5: return enrolled;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: code = (java.lang.CharSequence)value$; break;
    case 3: professorId = (java.lang.Integer)value$; break;
    case 4: capacity = (java.lang.Integer)value$; break;
    case 5: enrolled = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'code' field.
   * @return The value of the 'code' field.
   */
  public java.lang.CharSequence getCode() {
    return code;
  }


  /**
   * Sets the value of the 'code' field.
   * @param value the value to set.
   */
  public void setCode(java.lang.CharSequence value) {
    this.code = value;
  }

  /**
   * Gets the value of the 'professorId' field.
   * @return The value of the 'professorId' field.
   */
  public int getProfessorId() {
    return professorId;
  }


  /**
   * Sets the value of the 'professorId' field.
   * @param value the value to set.
   */
  public void setProfessorId(int value) {
    this.professorId = value;
  }

  /**
   * Gets the value of the 'capacity' field.
   * @return The value of the 'capacity' field.
   */
  public int getCapacity() {
    return capacity;
  }


  /**
   * Sets the value of the 'capacity' field.
   * @param value the value to set.
   */
  public void setCapacity(int value) {
    this.capacity = value;
  }

  /**
   * Gets the value of the 'enrolled' field.
   * @return The value of the 'enrolled' field.
   */
  public java.lang.Integer getEnrolled() {
    return enrolled;
  }


  /**
   * Sets the value of the 'enrolled' field.
   * @param value the value to set.
   */
  public void setEnrolled(java.lang.Integer value) {
    this.enrolled = value;
  }

  /**
   * Creates a new Course RecordBuilder.
   * @return A new Course RecordBuilder
   */
  public static com.courseselection.kafkatypes.Course.Builder newBuilder() {
    return new com.courseselection.kafkatypes.Course.Builder();
  }

  /**
   * Creates a new Course RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Course RecordBuilder
   */
  public static com.courseselection.kafkatypes.Course.Builder newBuilder(com.courseselection.kafkatypes.Course.Builder other) {
    if (other == null) {
      return new com.courseselection.kafkatypes.Course.Builder();
    } else {
      return new com.courseselection.kafkatypes.Course.Builder(other);
    }
  }

  /**
   * Creates a new Course RecordBuilder by copying an existing Course instance.
   * @param other The existing instance to copy.
   * @return A new Course RecordBuilder
   */
  public static com.courseselection.kafkatypes.Course.Builder newBuilder(com.courseselection.kafkatypes.Course other) {
    if (other == null) {
      return new com.courseselection.kafkatypes.Course.Builder();
    } else {
      return new com.courseselection.kafkatypes.Course.Builder(other);
    }
  }

  /**
   * RecordBuilder for Course instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Course>
    implements org.apache.avro.data.RecordBuilder<Course> {

    private java.lang.Integer id;
    private java.lang.CharSequence name;
    private java.lang.CharSequence code;
    private int professorId;
    private int capacity;
    private java.lang.Integer enrolled;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.courseselection.kafkatypes.Course.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.code)) {
        this.code = data().deepCopy(fields()[2].schema(), other.code);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.professorId)) {
        this.professorId = data().deepCopy(fields()[3].schema(), other.professorId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.capacity)) {
        this.capacity = data().deepCopy(fields()[4].schema(), other.capacity);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.enrolled)) {
        this.enrolled = data().deepCopy(fields()[5].schema(), other.enrolled);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing Course instance
     * @param other The existing instance to copy.
     */
    private Builder(com.courseselection.kafkatypes.Course other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.code)) {
        this.code = data().deepCopy(fields()[2].schema(), other.code);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.professorId)) {
        this.professorId = data().deepCopy(fields()[3].schema(), other.professorId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.capacity)) {
        this.capacity = data().deepCopy(fields()[4].schema(), other.capacity);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.enrolled)) {
        this.enrolled = data().deepCopy(fields()[5].schema(), other.enrolled);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Integer getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.Course.Builder setId(java.lang.Integer value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.Course.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.Course.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.Course.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'code' field.
      * @return The value.
      */
    public java.lang.CharSequence getCode() {
      return code;
    }


    /**
      * Sets the value of the 'code' field.
      * @param value The value of 'code'.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.Course.Builder setCode(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.code = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'code' field has been set.
      * @return True if the 'code' field has been set, false otherwise.
      */
    public boolean hasCode() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'code' field.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.Course.Builder clearCode() {
      code = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'professorId' field.
      * @return The value.
      */
    public int getProfessorId() {
      return professorId;
    }


    /**
      * Sets the value of the 'professorId' field.
      * @param value The value of 'professorId'.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.Course.Builder setProfessorId(int value) {
      validate(fields()[3], value);
      this.professorId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'professorId' field has been set.
      * @return True if the 'professorId' field has been set, false otherwise.
      */
    public boolean hasProfessorId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'professorId' field.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.Course.Builder clearProfessorId() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'capacity' field.
      * @return The value.
      */
    public int getCapacity() {
      return capacity;
    }


    /**
      * Sets the value of the 'capacity' field.
      * @param value The value of 'capacity'.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.Course.Builder setCapacity(int value) {
      validate(fields()[4], value);
      this.capacity = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'capacity' field has been set.
      * @return True if the 'capacity' field has been set, false otherwise.
      */
    public boolean hasCapacity() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'capacity' field.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.Course.Builder clearCapacity() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'enrolled' field.
      * @return The value.
      */
    public java.lang.Integer getEnrolled() {
      return enrolled;
    }


    /**
      * Sets the value of the 'enrolled' field.
      * @param value The value of 'enrolled'.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.Course.Builder setEnrolled(java.lang.Integer value) {
      validate(fields()[5], value);
      this.enrolled = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'enrolled' field has been set.
      * @return True if the 'enrolled' field has been set, false otherwise.
      */
    public boolean hasEnrolled() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'enrolled' field.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.Course.Builder clearEnrolled() {
      enrolled = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Course build() {
      try {
        Course record = new Course();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.code = fieldSetFlags()[2] ? this.code : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.professorId = fieldSetFlags()[3] ? this.professorId : (java.lang.Integer) defaultValue(fields()[3]);
        record.capacity = fieldSetFlags()[4] ? this.capacity : (java.lang.Integer) defaultValue(fields()[4]);
        record.enrolled = fieldSetFlags()[5] ? this.enrolled : (java.lang.Integer) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Course>
    WRITER$ = (org.apache.avro.io.DatumWriter<Course>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Course>
    READER$ = (org.apache.avro.io.DatumReader<Course>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.id == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeInt(this.id);
    }

    out.writeString(this.name);

    out.writeString(this.code);

    out.writeInt(this.professorId);

    out.writeInt(this.capacity);

    if (this.enrolled == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeInt(this.enrolled);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 0) {
        in.readNull();
        this.id = null;
      } else {
        this.id = in.readInt();
      }

      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      this.code = in.readString(this.code instanceof Utf8 ? (Utf8)this.code : null);

      this.professorId = in.readInt();

      this.capacity = in.readInt();

      if (in.readIndex() != 0) {
        in.readNull();
        this.enrolled = null;
      } else {
        this.enrolled = in.readInt();
      }

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 0) {
            in.readNull();
            this.id = null;
          } else {
            this.id = in.readInt();
          }
          break;

        case 1:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 2:
          this.code = in.readString(this.code instanceof Utf8 ? (Utf8)this.code : null);
          break;

        case 3:
          this.professorId = in.readInt();
          break;

        case 4:
          this.capacity = in.readInt();
          break;

        case 5:
          if (in.readIndex() != 0) {
            in.readNull();
            this.enrolled = null;
          } else {
            this.enrolled = in.readInt();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










