/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.courseselection.kafkatypes;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CourseOperation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5966542801151382624L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CourseOperation\",\"namespace\":\"com.courseselection.kafkatypes\",\"fields\":[{\"name\":\"operation\",\"type\":\"string\"},{\"name\":\"course\",\"type\":[{\"type\":\"record\",\"name\":\"Course\",\"fields\":[{\"name\":\"id\",\"type\":[\"int\",\"null\"]},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"code\",\"type\":\"string\"},{\"name\":\"professorId\",\"type\":\"int\"},{\"name\":\"capacity\",\"type\":\"int\"},{\"name\":\"enrolled\",\"type\":[\"int\",\"null\"]}]},\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CourseOperation> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CourseOperation> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CourseOperation> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CourseOperation> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CourseOperation> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CourseOperation to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CourseOperation from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CourseOperation instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CourseOperation fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence operation;
  private com.courseselection.kafkatypes.Course course;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CourseOperation() {}

  /**
   * All-args constructor.
   * @param operation The new value for operation
   * @param course The new value for course
   */
  public CourseOperation(java.lang.CharSequence operation, com.courseselection.kafkatypes.Course course) {
    this.operation = operation;
    this.course = course;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return operation;
    case 1: return course;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: operation = (java.lang.CharSequence)value$; break;
    case 1: course = (com.courseselection.kafkatypes.Course)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'operation' field.
   * @return The value of the 'operation' field.
   */
  public java.lang.CharSequence getOperation() {
    return operation;
  }


  /**
   * Sets the value of the 'operation' field.
   * @param value the value to set.
   */
  public void setOperation(java.lang.CharSequence value) {
    this.operation = value;
  }

  /**
   * Gets the value of the 'course' field.
   * @return The value of the 'course' field.
   */
  public com.courseselection.kafkatypes.Course getCourse() {
    return course;
  }


  /**
   * Sets the value of the 'course' field.
   * @param value the value to set.
   */
  public void setCourse(com.courseselection.kafkatypes.Course value) {
    this.course = value;
  }

  /**
   * Creates a new CourseOperation RecordBuilder.
   * @return A new CourseOperation RecordBuilder
   */
  public static com.courseselection.kafkatypes.CourseOperation.Builder newBuilder() {
    return new com.courseselection.kafkatypes.CourseOperation.Builder();
  }

  /**
   * Creates a new CourseOperation RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CourseOperation RecordBuilder
   */
  public static com.courseselection.kafkatypes.CourseOperation.Builder newBuilder(com.courseselection.kafkatypes.CourseOperation.Builder other) {
    if (other == null) {
      return new com.courseselection.kafkatypes.CourseOperation.Builder();
    } else {
      return new com.courseselection.kafkatypes.CourseOperation.Builder(other);
    }
  }

  /**
   * Creates a new CourseOperation RecordBuilder by copying an existing CourseOperation instance.
   * @param other The existing instance to copy.
   * @return A new CourseOperation RecordBuilder
   */
  public static com.courseselection.kafkatypes.CourseOperation.Builder newBuilder(com.courseselection.kafkatypes.CourseOperation other) {
    if (other == null) {
      return new com.courseselection.kafkatypes.CourseOperation.Builder();
    } else {
      return new com.courseselection.kafkatypes.CourseOperation.Builder(other);
    }
  }

  /**
   * RecordBuilder for CourseOperation instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CourseOperation>
    implements org.apache.avro.data.RecordBuilder<CourseOperation> {

    private java.lang.CharSequence operation;
    private com.courseselection.kafkatypes.Course course;
    private com.courseselection.kafkatypes.Course.Builder courseBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.courseselection.kafkatypes.CourseOperation.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.operation)) {
        this.operation = data().deepCopy(fields()[0].schema(), other.operation);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.course)) {
        this.course = data().deepCopy(fields()[1].schema(), other.course);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (other.hasCourseBuilder()) {
        this.courseBuilder = com.courseselection.kafkatypes.Course.newBuilder(other.getCourseBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing CourseOperation instance
     * @param other The existing instance to copy.
     */
    private Builder(com.courseselection.kafkatypes.CourseOperation other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.operation)) {
        this.operation = data().deepCopy(fields()[0].schema(), other.operation);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.course)) {
        this.course = data().deepCopy(fields()[1].schema(), other.course);
        fieldSetFlags()[1] = true;
      }
      this.courseBuilder = null;
    }

    /**
      * Gets the value of the 'operation' field.
      * @return The value.
      */
    public java.lang.CharSequence getOperation() {
      return operation;
    }


    /**
      * Sets the value of the 'operation' field.
      * @param value The value of 'operation'.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.CourseOperation.Builder setOperation(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.operation = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'operation' field has been set.
      * @return True if the 'operation' field has been set, false otherwise.
      */
    public boolean hasOperation() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'operation' field.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.CourseOperation.Builder clearOperation() {
      operation = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'course' field.
      * @return The value.
      */
    public com.courseselection.kafkatypes.Course getCourse() {
      return course;
    }


    /**
      * Sets the value of the 'course' field.
      * @param value The value of 'course'.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.CourseOperation.Builder setCourse(com.courseselection.kafkatypes.Course value) {
      validate(fields()[1], value);
      this.courseBuilder = null;
      this.course = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'course' field has been set.
      * @return True if the 'course' field has been set, false otherwise.
      */
    public boolean hasCourse() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'course' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.courseselection.kafkatypes.Course.Builder getCourseBuilder() {
      if (courseBuilder == null) {
        if (hasCourse()) {
          setCourseBuilder(com.courseselection.kafkatypes.Course.newBuilder(course));
        } else {
          setCourseBuilder(com.courseselection.kafkatypes.Course.newBuilder());
        }
      }
      return courseBuilder;
    }

    /**
     * Sets the Builder instance for the 'course' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.courseselection.kafkatypes.CourseOperation.Builder setCourseBuilder(com.courseselection.kafkatypes.Course.Builder value) {
      clearCourse();
      courseBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'course' field has an active Builder instance
     * @return True if the 'course' field has an active Builder instance
     */
    public boolean hasCourseBuilder() {
      return courseBuilder != null;
    }

    /**
      * Clears the value of the 'course' field.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.CourseOperation.Builder clearCourse() {
      course = null;
      courseBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CourseOperation build() {
      try {
        CourseOperation record = new CourseOperation();
        record.operation = fieldSetFlags()[0] ? this.operation : (java.lang.CharSequence) defaultValue(fields()[0]);
        if (courseBuilder != null) {
          try {
            record.course = this.courseBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("course"));
            throw e;
          }
        } else {
          record.course = fieldSetFlags()[1] ? this.course : (com.courseselection.kafkatypes.Course) defaultValue(fields()[1]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CourseOperation>
    WRITER$ = (org.apache.avro.io.DatumWriter<CourseOperation>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CourseOperation>
    READER$ = (org.apache.avro.io.DatumReader<CourseOperation>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.operation);

    if (this.course == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      this.course.customEncode(out);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.operation = in.readString(this.operation instanceof Utf8 ? (Utf8)this.operation : null);

      if (in.readIndex() != 0) {
        in.readNull();
        this.course = null;
      } else {
        if (this.course == null) {
          this.course = new com.courseselection.kafkatypes.Course();
        }
        this.course.customDecode(in);
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.operation = in.readString(this.operation instanceof Utf8 ? (Utf8)this.operation : null);
          break;

        case 1:
          if (in.readIndex() != 0) {
            in.readNull();
            this.course = null;
          } else {
            if (this.course == null) {
              this.course = new com.courseselection.kafkatypes.Course();
            }
            this.course.customDecode(in);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










