/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.courseselection.kafkatypes;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DropRequest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6727967377400922268L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DropRequest\",\"namespace\":\"com.courseselection.kafkatypes\",\"fields\":[{\"name\":\"course_id\",\"type\":\"int\"},{\"name\":\"student_id\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DropRequest> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DropRequest> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DropRequest> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DropRequest> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DropRequest> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DropRequest to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DropRequest from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DropRequest instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DropRequest fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int course_id;
  private int student_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DropRequest() {}

  /**
   * All-args constructor.
   * @param course_id The new value for course_id
   * @param student_id The new value for student_id
   */
  public DropRequest(java.lang.Integer course_id, java.lang.Integer student_id) {
    this.course_id = course_id;
    this.student_id = student_id;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return course_id;
    case 1: return student_id;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: course_id = (java.lang.Integer)value$; break;
    case 1: student_id = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'course_id' field.
   * @return The value of the 'course_id' field.
   */
  public int getCourseId() {
    return course_id;
  }


  /**
   * Sets the value of the 'course_id' field.
   * @param value the value to set.
   */
  public void setCourseId(int value) {
    this.course_id = value;
  }

  /**
   * Gets the value of the 'student_id' field.
   * @return The value of the 'student_id' field.
   */
  public int getStudentId() {
    return student_id;
  }


  /**
   * Sets the value of the 'student_id' field.
   * @param value the value to set.
   */
  public void setStudentId(int value) {
    this.student_id = value;
  }

  /**
   * Creates a new DropRequest RecordBuilder.
   * @return A new DropRequest RecordBuilder
   */
  public static com.courseselection.kafkatypes.DropRequest.Builder newBuilder() {
    return new com.courseselection.kafkatypes.DropRequest.Builder();
  }

  /**
   * Creates a new DropRequest RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DropRequest RecordBuilder
   */
  public static com.courseselection.kafkatypes.DropRequest.Builder newBuilder(com.courseselection.kafkatypes.DropRequest.Builder other) {
    if (other == null) {
      return new com.courseselection.kafkatypes.DropRequest.Builder();
    } else {
      return new com.courseselection.kafkatypes.DropRequest.Builder(other);
    }
  }

  /**
   * Creates a new DropRequest RecordBuilder by copying an existing DropRequest instance.
   * @param other The existing instance to copy.
   * @return A new DropRequest RecordBuilder
   */
  public static com.courseselection.kafkatypes.DropRequest.Builder newBuilder(com.courseselection.kafkatypes.DropRequest other) {
    if (other == null) {
      return new com.courseselection.kafkatypes.DropRequest.Builder();
    } else {
      return new com.courseselection.kafkatypes.DropRequest.Builder(other);
    }
  }

  /**
   * RecordBuilder for DropRequest instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DropRequest>
    implements org.apache.avro.data.RecordBuilder<DropRequest> {

    private int course_id;
    private int student_id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.courseselection.kafkatypes.DropRequest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.course_id)) {
        this.course_id = data().deepCopy(fields()[0].schema(), other.course_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.student_id)) {
        this.student_id = data().deepCopy(fields()[1].schema(), other.student_id);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing DropRequest instance
     * @param other The existing instance to copy.
     */
    private Builder(com.courseselection.kafkatypes.DropRequest other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.course_id)) {
        this.course_id = data().deepCopy(fields()[0].schema(), other.course_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.student_id)) {
        this.student_id = data().deepCopy(fields()[1].schema(), other.student_id);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'course_id' field.
      * @return The value.
      */
    public int getCourseId() {
      return course_id;
    }


    /**
      * Sets the value of the 'course_id' field.
      * @param value The value of 'course_id'.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.DropRequest.Builder setCourseId(int value) {
      validate(fields()[0], value);
      this.course_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'course_id' field has been set.
      * @return True if the 'course_id' field has been set, false otherwise.
      */
    public boolean hasCourseId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'course_id' field.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.DropRequest.Builder clearCourseId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'student_id' field.
      * @return The value.
      */
    public int getStudentId() {
      return student_id;
    }


    /**
      * Sets the value of the 'student_id' field.
      * @param value The value of 'student_id'.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.DropRequest.Builder setStudentId(int value) {
      validate(fields()[1], value);
      this.student_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'student_id' field has been set.
      * @return True if the 'student_id' field has been set, false otherwise.
      */
    public boolean hasStudentId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'student_id' field.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.DropRequest.Builder clearStudentId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DropRequest build() {
      try {
        DropRequest record = new DropRequest();
        record.course_id = fieldSetFlags()[0] ? this.course_id : (java.lang.Integer) defaultValue(fields()[0]);
        record.student_id = fieldSetFlags()[1] ? this.student_id : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DropRequest>
    WRITER$ = (org.apache.avro.io.DatumWriter<DropRequest>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DropRequest>
    READER$ = (org.apache.avro.io.DatumReader<DropRequest>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.course_id);

    out.writeInt(this.student_id);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.course_id = in.readInt();

      this.student_id = in.readInt();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.course_id = in.readInt();
          break;

        case 1:
          this.student_id = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










