/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.courseselection.kafkatypes;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class EnrollmentDropResponse extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2257769828906001634L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EnrollmentDropResponse\",\"namespace\":\"com.courseselection.kafkatypes\",\"fields\":[{\"name\":\"status\",\"type\":\"string\"},{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"message\",\"type\":\"string\"},{\"name\":\"course_id\",\"type\":\"int\"},{\"name\":\"student_id\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EnrollmentDropResponse> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EnrollmentDropResponse> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<EnrollmentDropResponse> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<EnrollmentDropResponse> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<EnrollmentDropResponse> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this EnrollmentDropResponse to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a EnrollmentDropResponse from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a EnrollmentDropResponse instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static EnrollmentDropResponse fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence status;
  private java.lang.CharSequence type;
  private java.lang.CharSequence message;
  private int course_id;
  private int student_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EnrollmentDropResponse() {}

  /**
   * All-args constructor.
   * @param status The new value for status
   * @param type The new value for type
   * @param message The new value for message
   * @param course_id The new value for course_id
   * @param student_id The new value for student_id
   */
  public EnrollmentDropResponse(java.lang.CharSequence status, java.lang.CharSequence type, java.lang.CharSequence message, java.lang.Integer course_id, java.lang.Integer student_id) {
    this.status = status;
    this.type = type;
    this.message = message;
    this.course_id = course_id;
    this.student_id = student_id;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return status;
    case 1: return type;
    case 2: return message;
    case 3: return course_id;
    case 4: return student_id;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: status = (java.lang.CharSequence)value$; break;
    case 1: type = (java.lang.CharSequence)value$; break;
    case 2: message = (java.lang.CharSequence)value$; break;
    case 3: course_id = (java.lang.Integer)value$; break;
    case 4: student_id = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.CharSequence getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.CharSequence value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.CharSequence getType() {
    return type;
  }


  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.CharSequence value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'message' field.
   * @return The value of the 'message' field.
   */
  public java.lang.CharSequence getMessage() {
    return message;
  }


  /**
   * Sets the value of the 'message' field.
   * @param value the value to set.
   */
  public void setMessage(java.lang.CharSequence value) {
    this.message = value;
  }

  /**
   * Gets the value of the 'course_id' field.
   * @return The value of the 'course_id' field.
   */
  public int getCourseId() {
    return course_id;
  }


  /**
   * Sets the value of the 'course_id' field.
   * @param value the value to set.
   */
  public void setCourseId(int value) {
    this.course_id = value;
  }

  /**
   * Gets the value of the 'student_id' field.
   * @return The value of the 'student_id' field.
   */
  public int getStudentId() {
    return student_id;
  }


  /**
   * Sets the value of the 'student_id' field.
   * @param value the value to set.
   */
  public void setStudentId(int value) {
    this.student_id = value;
  }

  /**
   * Creates a new EnrollmentDropResponse RecordBuilder.
   * @return A new EnrollmentDropResponse RecordBuilder
   */
  public static com.courseselection.kafkatypes.EnrollmentDropResponse.Builder newBuilder() {
    return new com.courseselection.kafkatypes.EnrollmentDropResponse.Builder();
  }

  /**
   * Creates a new EnrollmentDropResponse RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EnrollmentDropResponse RecordBuilder
   */
  public static com.courseselection.kafkatypes.EnrollmentDropResponse.Builder newBuilder(com.courseselection.kafkatypes.EnrollmentDropResponse.Builder other) {
    if (other == null) {
      return new com.courseselection.kafkatypes.EnrollmentDropResponse.Builder();
    } else {
      return new com.courseselection.kafkatypes.EnrollmentDropResponse.Builder(other);
    }
  }

  /**
   * Creates a new EnrollmentDropResponse RecordBuilder by copying an existing EnrollmentDropResponse instance.
   * @param other The existing instance to copy.
   * @return A new EnrollmentDropResponse RecordBuilder
   */
  public static com.courseselection.kafkatypes.EnrollmentDropResponse.Builder newBuilder(com.courseselection.kafkatypes.EnrollmentDropResponse other) {
    if (other == null) {
      return new com.courseselection.kafkatypes.EnrollmentDropResponse.Builder();
    } else {
      return new com.courseselection.kafkatypes.EnrollmentDropResponse.Builder(other);
    }
  }

  /**
   * RecordBuilder for EnrollmentDropResponse instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EnrollmentDropResponse>
    implements org.apache.avro.data.RecordBuilder<EnrollmentDropResponse> {

    private java.lang.CharSequence status;
    private java.lang.CharSequence type;
    private java.lang.CharSequence message;
    private int course_id;
    private int student_id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.courseselection.kafkatypes.EnrollmentDropResponse.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.status)) {
        this.status = data().deepCopy(fields()[0].schema(), other.status);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.message)) {
        this.message = data().deepCopy(fields()[2].schema(), other.message);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.course_id)) {
        this.course_id = data().deepCopy(fields()[3].schema(), other.course_id);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.student_id)) {
        this.student_id = data().deepCopy(fields()[4].schema(), other.student_id);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing EnrollmentDropResponse instance
     * @param other The existing instance to copy.
     */
    private Builder(com.courseselection.kafkatypes.EnrollmentDropResponse other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.status)) {
        this.status = data().deepCopy(fields()[0].schema(), other.status);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.message)) {
        this.message = data().deepCopy(fields()[2].schema(), other.message);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.course_id)) {
        this.course_id = data().deepCopy(fields()[3].schema(), other.course_id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.student_id)) {
        this.student_id = data().deepCopy(fields()[4].schema(), other.student_id);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.EnrollmentDropResponse.Builder setStatus(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.status = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.EnrollmentDropResponse.Builder clearStatus() {
      status = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.CharSequence getType() {
      return type;
    }


    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.EnrollmentDropResponse.Builder setType(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.type = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.EnrollmentDropResponse.Builder clearType() {
      type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'message' field.
      * @return The value.
      */
    public java.lang.CharSequence getMessage() {
      return message;
    }


    /**
      * Sets the value of the 'message' field.
      * @param value The value of 'message'.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.EnrollmentDropResponse.Builder setMessage(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.message = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'message' field has been set.
      * @return True if the 'message' field has been set, false otherwise.
      */
    public boolean hasMessage() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'message' field.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.EnrollmentDropResponse.Builder clearMessage() {
      message = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'course_id' field.
      * @return The value.
      */
    public int getCourseId() {
      return course_id;
    }


    /**
      * Sets the value of the 'course_id' field.
      * @param value The value of 'course_id'.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.EnrollmentDropResponse.Builder setCourseId(int value) {
      validate(fields()[3], value);
      this.course_id = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'course_id' field has been set.
      * @return True if the 'course_id' field has been set, false otherwise.
      */
    public boolean hasCourseId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'course_id' field.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.EnrollmentDropResponse.Builder clearCourseId() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'student_id' field.
      * @return The value.
      */
    public int getStudentId() {
      return student_id;
    }


    /**
      * Sets the value of the 'student_id' field.
      * @param value The value of 'student_id'.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.EnrollmentDropResponse.Builder setStudentId(int value) {
      validate(fields()[4], value);
      this.student_id = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'student_id' field has been set.
      * @return True if the 'student_id' field has been set, false otherwise.
      */
    public boolean hasStudentId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'student_id' field.
      * @return This builder.
      */
    public com.courseselection.kafkatypes.EnrollmentDropResponse.Builder clearStudentId() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EnrollmentDropResponse build() {
      try {
        EnrollmentDropResponse record = new EnrollmentDropResponse();
        record.status = fieldSetFlags()[0] ? this.status : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.type = fieldSetFlags()[1] ? this.type : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.message = fieldSetFlags()[2] ? this.message : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.course_id = fieldSetFlags()[3] ? this.course_id : (java.lang.Integer) defaultValue(fields()[3]);
        record.student_id = fieldSetFlags()[4] ? this.student_id : (java.lang.Integer) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EnrollmentDropResponse>
    WRITER$ = (org.apache.avro.io.DatumWriter<EnrollmentDropResponse>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EnrollmentDropResponse>
    READER$ = (org.apache.avro.io.DatumReader<EnrollmentDropResponse>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.status);

    out.writeString(this.type);

    out.writeString(this.message);

    out.writeInt(this.course_id);

    out.writeInt(this.student_id);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.status = in.readString(this.status instanceof Utf8 ? (Utf8)this.status : null);

      this.type = in.readString(this.type instanceof Utf8 ? (Utf8)this.type : null);

      this.message = in.readString(this.message instanceof Utf8 ? (Utf8)this.message : null);

      this.course_id = in.readInt();

      this.student_id = in.readInt();

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.status = in.readString(this.status instanceof Utf8 ? (Utf8)this.status : null);
          break;

        case 1:
          this.type = in.readString(this.type instanceof Utf8 ? (Utf8)this.type : null);
          break;

        case 2:
          this.message = in.readString(this.message instanceof Utf8 ? (Utf8)this.message : null);
          break;

        case 3:
          this.course_id = in.readInt();
          break;

        case 4:
          this.student_id = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










